site_name: JackPot Docs
repo_url: https://github.com/cadayton/JackPot
theme: readthedocs
pages:
  - Home: Home.md
  - Game Basics:
    - Game Menu: Game-Menu.md
    - Game Workflow: Game-Workflow.md
  - Installation & Setup:
    - Setup: Setup.md
    - Other Options: Other-Commands.md
    - Version History: Version-History.md
